# docker-compose.yml
# docker compose up && docker compose install/update
# docker compose build before every run
# docker exec -it react-resume-backend-postgres-1 psql -U postgres -d postgres -> on cmd to access postgres database
version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: projects
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - projects-db:/var/lib/postgresql/data

  projects:
    build:
      context: .
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
    depends_on: #doesnt run till postgres is running
      - postgres
    ports:
      - '8888:8888'
        
volumes:
  projects-db: